# Generated by Django 4.2.5 on 2023-11-15 01:13

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title', 'image'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=pages.models.custom_upload_to, verbose_name='Imagen'),
        ),
    ]
