# Generated by Django 4.2.5 on 2023-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='usuario',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
