# Generated by Django 4.2.5 on 2023-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas', '0002_remove_citamedica_usuario_citamedica_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='sasasasas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
