# Generated by Django 4.2.5 on 2023-11-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_alter_page_image'),
        ('citas_medicas', '0003_citamedica_sasasasas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='sasasasas',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Tipo de Examen'),
        ),
    ]
