# Generated by Django 4.2.5 on 2023-11-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas', '0004_remove_citamedica_sasasasas_citamedica_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
