# Generated by Django 4.2.5 on 2023-11-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_alter_page_image'),
        ('citas_medicas', '0005_citamedica_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='hora',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
    ]
